services:
  postgres:
    image: postgres:12-alpine
    container_name: interview-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interview
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - interview-network

  redis_server:
    image: redis:alpine
    container_name: interview-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --save "" --maxmemory-policy allkeys-lru
    networks:
      - interview-network

  interview-backend-server:
    container_name: interview-backend-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    networks:
      - interview-network
    depends_on:
      - postgres
      - redis_server
    environment:
      ENV: dev
      DB_SOURCE: postgresql://user:password@postgres:5432/interview?sslmode=disable
    entrypoint: ["/app/migration.sh", "postgres:5432", "--"]
    command: ["/app/main"]

networks:
  interview-network:
    external: true


