services:
  postgres:
    image: postgres:18-alpine
    container_name: ticket-reservation-server-db
    environment:
      POSTGRES_DB: ticket-reservation-server
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/18/data/pgdata
      TZ: "Asia/Bangkok"
    ports:
      - "5434:5432"
    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "max_connections=20000"
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ticket-reservation-server"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ticket-reservation-server-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge
