// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/guncv/ticket-reservation-server/internal/service/user/dto"
	mock "github.com/stretchr/testify/mock"

	token "github.com/guncv/ticket-reservation-server/internal/service/user/token"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

// CreateAdminUser provides a mock function with given fields: ctx, req
func (_m *MockUserService) CreateAdminUser(ctx context.Context, req dto.CreateUserReq) (dto.CreateUserResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdminUser")
	}

	var r0 dto.CreateUserResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserReq) (dto.CreateUserResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserReq) dto.CreateUserResp); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CreateUserResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateUserReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, req
func (_m *MockUserService) CreateUser(ctx context.Context, req dto.CreateUserReq) (dto.CreateUserResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 dto.CreateUserResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserReq) (dto.CreateUserResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserReq) dto.CreateUserResp); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CreateUserResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateUserReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginUser provides a mock function with given fields: ctx, req
func (_m *MockUserService) LoginUser(ctx context.Context, req dto.LoginUserReq) (dto.LoginUserResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 dto.LoginUserResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginUserReq) (dto.LoginUserResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginUserReq) dto.LoginUserResp); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.LoginUserResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LoginUserReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogoutUser provides a mock function with given fields: ctx
func (_m *MockUserService) LogoutUser(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LogoutUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyAndRenewToken provides a mock function with given fields: ctx, req
func (_m *MockUserService) VerifyAndRenewToken(ctx context.Context, req dto.SessionReq) (dto.SessionResp, token.TokenPayload, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAndRenewToken")
	}

	var r0 dto.SessionResp
	var r1 token.TokenPayload
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SessionReq) (dto.SessionResp, token.TokenPayload, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SessionReq) dto.SessionResp); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.SessionResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SessionReq) token.TokenPayload); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(token.TokenPayload)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.SessionReq) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
